//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;

public class Koe
{
	public int AantalLitersMelk
	{
		get;
		set;
	}

	public virtual Size Afmetingen
	{
		get;
		private set;
	}

	public virtual DateTime GeboorteDatum
	{
		get;
		set;
	}

	public virtual double Gewicht
	{
		get;
		set;
	}

	public virtual double GewichtMaximaal
	{
		get;
		private set;
	}

	public virtual Color Kleur
	{
		get;
		set;
	}

	public virtual string LatijnseNaam
	{
		get;
		private set;
	}

	public virtual int Leeftijd
	{
		get;
		set;
	}

	public virtual int Levensduur
	{
		get;
		private set;
	}

	public virtual Point Locatie
	{
		get;
		set;
	}

	public virtual int MaagGevuld
	{
		get;
		set;
	}

	public virtual string Naam
	{
		get;
		set;
	}

	public virtual string NederlandseNaam
	{
		get;
		private set;
	}

	public virtual int RichtingX
	{
		get;
		set;
	}

	public virtual int RichtingY
	{
		get;
		set;
	}

	public virtual DateTime SterfDatum
	{
		get;
		set;
	}

	public virtual Timer Verouder
	{
		get;
		private set;
	}

	public virtual bool Verwijderd
	{
		get;
		private set;
	}

	public virtual int Voedingswaarde
	{
		get;
		set;
	}

	public virtual List<string> WordtVergiftigdDoor
	{
		get;
		private set;
	}

	private Size _afmetingen
	{
		get;
		set;
	}

	private double _gewichtMaximaal
	{
		get;
		set;
	}

	private List<string> _wordtVergiftigdDoor
	{
		get;
		set;
	}

}

