//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Drawing;
using System.Windows.Forms;

namespace NatSimII
{

    public class Koe : Planteneter
    {
        public Koe() : base(_verhoudingsTicksJaren, _latijnseNaam, _leeftijd, _gewichtMaximaal)
        {
            InitClass(new Point(0, 0), "", Color.Brown);
        }
        public Koe(Point locatie) : base(_verhoudingsTicksJaren, _latijnseNaam, _leeftijd, _gewichtMaximaal)
        {
            InitClass(locatie, "", Color.Brown);
        }
        public Koe(Point locatie, string naam, Color kleur) : base(_verhoudingsTicksJaren, _latijnseNaam, _leeftijd, _gewichtMaximaal)
        {
            InitClass(locatie, naam, kleur);
        }

        private void InitClass(Point locatie, string naam, Color kleur)
        {
            Locatie = locatie;
            Naam = naam;
            Kleur = kleur;
            Tekengebied.Afmetingen = new Size(10, 10);
            Gewicht = 5;
            Voedingswaarde = 1;
        }

        private const string _latijnseNaam = "Bos Taurus";
        private const int _leeftijd = 25;
        private const int _verhoudingsTicksJaren = 1;
        private const double _gewichtMaximaal = 800;

        public int AantalLitersMelk { get; set; }
        public string Naam { get; set; }
        public double Gewicht { get; set; }
        public DateTime Geboortedatum { get; set; }
        public DateTime Sterfdatum { get; set; }
    }
}